# This workflow will upload an pesptool Python package when a release is created

name: PyPI release

on:
  release:
    types: [released]

jobs:
  build_and_upload:

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/pesptool

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.13
      uses: actions/setup-python@master
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build pesptool ${{ github.event.release.tag_name }}
      run: |
        echo "Packaging pesptool version: $(python setup.py --version 2>/dev/null)"
        python -m build --sdist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
